config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'home#index'

  #devise and omniauth
  get "login", to: redirect('auth/dreamvalley'), as: :login
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, skip: [:sessions]

  as :user do
    get '/auth/mindvalley', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :goals, only: [:new, :create]
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user

  validates :category, :description, :user, presence: true

  extend Enumerize
  enumerize :category, in: [:experience, :growth, :contribution], predicates: true, scope: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:mindvalley]

  def self.authorised?(user)
    user.email.ends_with?("@mindvalley.com" || "@mindvalleysupport.com")
  end

  def self.from_omniauth(auth)
    user = where(provider: auth["provider"], uid: auth["uid"].to_s).first || where(email: auth["info"]["email"]).first || self.new()
    user.assign_from_omniauth(auth)
    if User.authorised?(user)
      return user
    else
      return nil
    end
  end

  def assign_from_omniauth(auth)
    self.provider = auth["provider"]
    self.uid = auth["uid"]
    self.first_name = auth["info"]["first_name"]
    self.last_name = auth['info']['last_name']
    self.email = auth["info"]["email"]
    self.token = auth["credentials"]["token"]
    self.id_token = auth["credentials"]["id_token"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
  end

  def create
    goal = Goal.new(goal_params)
    goal.user_id = current_user.id
    if goal.save
      flash[:success] = "Successfully added goal!"
      redirect_to root_path
    else
      flash[:error] = 'Problem saving new goal. :('
      render :new
    end
  end

  private

  def goal_params
    params.require(:goal).permit(:category, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  def index
    @random_goals = Goal.order("RANDOM()").first(8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
  Questions = [
    ['What do I want to experience in life?', 'experience'],
    ['How do I want to grow?', 'growth'],
    ['How do I want to contribute to the planet?', 'contribution']
  ]
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/goals/new.html.erb
<%= form_for :goal, url: goals_path do |f| %>
  <%= f.select :category, GoalsHelper::Questions %>
  <%= f.text_field :description, required: true %>
  <%= f.submit "Submit" %>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to Dreamvalley</h1>

<div>
<% @random_goals.each do |goal| %>
  <p><%= goal.description %> - <%= goal.user.email %></p>
<% end %>
</div>

<div>
  <%= link_to "Write your own today!", new_goal_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DreamvalleyTdd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
  <% if current_user %>
    <p><%= current_user.first_name %></p>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>